import React from "react";
import { LegalPage } from "../components/LegalPage";

export default function PrivacyPage() {
  return (
    <LegalPage eyebrow="PRIVACY NOTICE · VERSION 2026-08-24-V3" title="Privacy, in plain language." intro="NOLI Vendaz needs enough information to operate your account, verify you when a protected service requires it, route payments and refunds, and resolve problems. Verification is progressive rather than compulsory merely to browse or save a basic profile.">
      <section><h2>Account and identity data</h2><p>NOLI stores your Google account identifier, email, display name, the names you provide, any linked registered phone number, your selected identification type, country and verification status. NOLI does not retain the full identification number after you save it. It stores a non-reversible server-keyed fingerprint for uniqueness/matching plus the last four characters for masked display. The full identification number is sent to CPay Identity only when you explicitly request verification and have accepted the current identity-verification consent.</p></section>
      <section><h2>Phone verification</h2><p>Linking a phone is optional during initial setup. When you request verification, NOLI generates a short-lived one-time code and CPay Communications routes the SMS through its configured provider. Verification codes are not stored in readable form. A verified phone becomes mandatory before services that require it, including the current power-bank rental service.</p></section>
      <section><h2>Identity verification providers</h2><p>Identification format validation occurs in NOLI before any provider request. Validation only checks structure and never means an ID is verified. When you choose Verify, CPay Identity sends the necessary information to the provider configured and approved for the selected identification type. Only an authoritative verification result changes the identity state to Verified.</p></section>
      <section><h2>Service providers</h2><p>NOLI uses Google for account sign-in and CPay for communications, identity verification, payment and vending orchestration. CPay may route a request to an approved downstream SMS, identity or payment provider. These integrations receive only the data needed for the function being performed.</p></section>
      <section><h2>Payments and refunds</h2><p>CPay processes vending payments, payment status, refunds and settlement references. NOLI stores the references and customer-safe status needed to explain a rental. Full card numbers and CVVs are not stored by NOLI. Refunds are tied to the verified registered phone whenever the connected CPay vending contract supports that routing.</p></section>
      <section><h2>Camera and location</h2><p>Camera access is requested only when you open the QR scanner, and the video feed is processed on the device rather than uploaded by NOLI. Location is requested only when you ask for nearby stations and is used to calculate distance in the app.</p></section>
      <section><h2>Rental and support records</h2><p>NOLI stores station, rental, pricing-snapshot, payment/refund references, lifecycle status and support information so the transaction can be explained and reconciled. Support text should never contain passwords, OTPs, PINs or full card numbers.</p></section>
      <section><h2>Retention</h2><p>Identity and account data should be retained only while needed to operate the account and meet approved legal or operational requirements. Transaction and reconciliation records may need to be retained after account deletion in anonymized form. The formal production retention schedule must be approved as part of launch compliance and applied consistently to operational systems and backups.</p></section>
      <section><h2>Account deletion</h2><p>You can request account deletion from Account. NOLI blocks deletion while a rental is still open. Once all rentals are terminal, identity, OAuth, session, notification and contact data are removed. Settled rental records are retained only in anonymized form for transaction reconciliation.</p></section>
    </LegalPage>
  );
}
