import React from "react";
import { LegalPage } from "../components/LegalPage";

export default function TermsPage() {
  return (
    <LegalPage eyebrow="CUSTOMER TERMS · VERSION 2026-08-24-V3" title="How a NOLI Vendaz account and rental work." intro="You may save a basic account before completing phone or identity verification. Protected services apply their verification requirements when you try to use them, before money or equipment moves.">
      <section><h2>Progressive verification</h2><p>Phone linkage and identification verification are optional during initial account setup unless a particular service requires them immediately. Before a protected service is granted, NOLI checks that the required phone and identification steps are complete. If not, the service remains blocked while you complete the missing verification and can then resume the original journey.</p></section>
      <section><h2>Validation and verification</h2><p>Validation checks whether a phone number or selected identification number has an acceptable structure. Verification is separate: phone verification requires the correct one-time SMS code, and identification verification requires an authoritative result through CPay Identity and the provider configured for that identification type. Passing a format check does not create verified status.</p></section>
      <section><h2>Eligibility and identity</h2><p>For the current power-bank rental service, you must use an authenticated NOLI Vendaz account, accept the current Terms and Privacy Notice, verify a registered phone, provide the required identity-verification consent, and hold an identification document that CPay Identity has authoritatively verified. Do not create or use an account for another person without authorization.</p></section>
      <section><h2>Starting a rental</h2><p>Before payment, NOLI checks the station, available inventory and pricing shown for the rental. Availability can change between viewing a station and starting a rental, so NOLI rechecks the connected vending service before collection. A payment confirmation alone does not prove a power bank was physically released.</p></section>
      <section><h2>Deposit, grace period and pricing</h2><p>The deposit, billing interval, grace period and daily cap shown before payment form the pricing basis presented for that rental. Those terms are saved with the rental so later station-price changes do not rewrite an existing transaction. The deposit is not the rental fee; the final charge and refundable amount are determined through the verified rental lifecycle.</p></section>
      <section><h2>Physical release</h2><p>NOLI treats the connected CPay vending service and vending provider as authoritative for physical release. If payment succeeds but release is uncertain, do not make another payment. The rental is reconciled or placed into review.</p></section>
      <section><h2>Returning a power bank</h2><p>Choose a compatible station with an open return slot, insert the power bank securely, and wait for provider verification. Selecting a station or tapping a return button does not itself end the rental.</p></section>
      <section><h2>Unreturned, lost or damaged equipment</h2><p>A rental remains open until the connected vending service verifies a return or the transaction is otherwise resolved. Any loss, replacement, damage or additional charge must follow the pricing and commercial policy disclosed for the service and the payment capability actually supported by CPay; NOLI does not invent an extra charge in the browser.</p></section>
      <section><h2>Refunds and additional charges</h2><p>Unused deposit may be refunded after a verified return and settlement. NOLI displays the registered refund destination before payment. Provider and financial-network processing can mean a refund is not visible instantly even after it is initiated. If the connected gateway cannot guarantee a separate payer and refund phone, NOLI requires payment from the registered phone instead.</p></section>
      <section><h2>Service availability</h2><p>A station may be offline, full, empty or temporarily unavailable. NOLI blocks a new collection when it cannot confirm a rentable station. If a rental is already financially or physically in progress, use the existing rental reference and status rather than starting a second transaction.</p></section>
      <section><h2>Safety and support</h2><p>Do not use visibly damaged equipment. Report failed release, damaged equipment, unconfirmed returns, payment issues or delayed refunds through the Support section so the rental reference and technical context remain attached to the case.</p></section>
    </LegalPage>
  );
}
